### ISSUE TITLE
Fix umlaut/unicode handling

### ISSUE THREAD

**Issue by razorheadfx** [razorheadfx/grup#3]
Right now there is just a markdown parsing step and the content being dumped to html.
Thus umlauts (and other unicode chars) break in the usual html way.

Potential Fixes:
Might be sufficient to set the charset to utf-8. (c.f. https://en.wikipedia.org/wiki/Unicode_and_HTML#Character_encoding_determination).
```
Content-Type: text/html; charset=UTF-8
```

Assumes:
- All users use utf-8 in the first place (seems reasonable enough at this point).

**Comment by NickeZ** [comment]
Actually fixed in both of my PRs. ;)

**Comment by razorheadfx** [comment]
Oh right ;D
Completely overlooked that when skimming your PR xD
Fixed in #1 then!
Cheers
